### PR TITLE
Linux has added a new capability audit_read

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by vmarmol** [comment]
:+1:

**Comment by crosbymichael** [comment]
@syndtr What do you think about defining the upper cap of 64 so that when new caps are added to the kernel, if we are using a whitelist, it will still be dropped without an update to the package?

**Comment by avagin** [comment]
@syndtr @crosbymichael I think we can get CAP_LAST_CAP from kernel.
$ cat /proc/sys/kernel/cap_last_cap 
37

**Comment by syndtr** [comment]
@crosbymichael agree with @avagin.

**Pull request merged**
